version: "3"

services:
  nextjs:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    entrypoint: ./.docker/entrypoint.sh
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
